language: csharp
dist: trusty
mono: none
dotnet: 2.1.301
os:
  - linux
  - osx
install:
- dotnet restore
script:
- dotnet build
- dotnet test src/UnitaryTests/UnitaryTests.csproj
-notifications:
-  email: false

