language: csharp
dist: trusty
mono: none
dotnet: 2.1.301
os:
  - linux
install:
- dotnet restore
script:
- dotnet build
- dotnet test src/UnitaryTests/UnitaryTests.csproj
git:
  submodules: false
before_install:
  - git submodule update --init
-notifications:
-  email: false